Repository Ricochet-Exchange/ricochet-frontend, pull requests merged in 2022-05, with the labels that each got.

#631 Feat: Add checkbox to hide low balance tokens
  src/containers/main/UpgradeContainer/index.tsx
  src/containers/main/UpgradeContainer/styles.module.scss
Labels: ready_to_review

#663 Relist V2 Markets
  src/components/streaming/StreamManagerItem/index.tsx
  src/constants/flowConfig.ts
  src/constants/polygon_config.js
  src/store/main/sagas/sweepQueryFlow.ts
  src/store/main/types.ts
  src/utils/getExchangeAddress.ts
Labels: ready_to_review

#661 feat: payments page
  src/components/layout/InvestNav/index.tsx
  src/components/layout/UserSettings/index.tsx
  src/components/streaming/RecentStreamActivity/styles.module.scss
  src/components/streaming/StreamForm/styles.module.scss
  src/components/streaming/StreamManager/index.tsx
  src/components/streaming/StreamManager/styles.module.scss
  src/components/streaming/StreamManagerItem/styles.module.scss
  src/constants/routes.ts
  src/containers/MainRouter/index.tsx
  src/containers/main/PaymentsContainer/index.tsx
  src/containers/main/PaymentsContainer/styles.module.scss
  src/containers/main/StreamContainer/index.tsx
  src/containers/main/StreamContainer/styles.module.scss
  src/pages/PaymentsPage/index.tsx
  src/pages/PaymentsPage/styles.module.scss
Labels: ready_to_review

#596 Create qa.yml
  .github/workflows/qa.yml
Labels: $500 bounty, under review

#595 add test.yml
  .github/workflows/test.yml
Labels: under review
